### PR TITLE
Support for modded items that contain water

### PR DESCRIPTION
**Pull request by cech12**
This PR changes the `isHoldingWater` method of the Collective library mod to support modded items that contain water.

Usecase: I am the developer of the BucketLib library mod and of Ceramic Bucket & Wooden Bucket. I would like to be compatible with your Transcending Trident mod and this PR does that. :)

### CODE REVIEW

**Comment by James103** [comment]
Have you tested this change at all? If so, does it work with
1) A vanilla water bucket?
2) A clay water bucket from the Ceramic Buckets mod and/or a wooden bucket filled with water from the Wooden Buckets mod?

**Comment by cech12** [comment]
Yes, vanilla Water Bucket, Ceramic Water Bucket & Wooden Water Bucket are working with this change. :)

**Comment by cech12** [comment]
@ricksouth I hope this PR hasn't been forgotten. :) I would be very happy if it can be merged. :)

**Comment by ricksouth** [comment]
Better late than never! I really appreciate the effort. I've merged the request and added the code changes to the other versions as well. Thank you!

**Pull request merged**
